title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: "true"
google_analytics: "false"
# theme: jekyll-theme-cayman
remote_theme: wchenyi/cayman
include:
  - assets
  - assets/js
  - assets/css
